# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SAS_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 528)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(0.965)
        MainWindow.setStyleSheet("background-color: rgb(30,30,30);\n"
"color: white; \n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_sidebar = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_sidebar.setContentsMargins(0, 9, 0, 9)
        self.verticalLayout_sidebar.setObjectName("verticalLayout_sidebar")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_sidebar.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_4.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_sidebar.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalFrame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_sidebar.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_sidebar.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.verticalFrame)
        self.panel_left = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel_left.sizePolicy().hasHeightForWidth())
        self.panel_left.setSizePolicy(sizePolicy)
        self.panel_left.setObjectName("panel_left")
        self.layout_left = QtWidgets.QVBoxLayout(self.panel_left)
        self.layout_left.setObjectName("layout_left")
        self.pushButton_inputDir = QtWidgets.QPushButton(self.panel_left)
        self.pushButton_inputDir.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton_inputDir.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(20, 51, 89);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(49, 110, 186);\n"
"}")
        self.pushButton_inputDir.setAutoDefault(False)
        self.pushButton_inputDir.setObjectName("pushButton_inputDir")
        self.layout_left.addWidget(self.pushButton_inputDir)
        self.textBrowser_inputDir = QtWidgets.QTextBrowser(self.panel_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_inputDir.sizePolicy().hasHeightForWidth())
        self.textBrowser_inputDir.setSizePolicy(sizePolicy)
        self.textBrowser_inputDir.setMaximumSize(QtCore.QSize(300, 40))
        self.textBrowser_inputDir.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_inputDir.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_inputDir.setOpenLinks(True)
        self.textBrowser_inputDir.setObjectName("textBrowser_inputDir")
        self.layout_left.addWidget(self.textBrowser_inputDir)
        self.line_topLeft = QtWidgets.QFrame(self.panel_left)
        self.line_topLeft.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_topLeft.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_topLeft.setObjectName("line_topLeft")
        self.layout_left.addWidget(self.line_topLeft)
        self.horizontalLayout_output = QtWidgets.QHBoxLayout()
        self.horizontalLayout_output.setObjectName("horizontalLayout_output")
        self.checkBox_saveToSameDir = QtWidgets.QCheckBox(self.panel_left)
        self.checkBox_saveToSameDir.setChecked(False)
        self.checkBox_saveToSameDir.setObjectName("checkBox_saveToSameDir")
        self.horizontalLayout_output.addWidget(self.checkBox_saveToSameDir)
        self.pushButton_outputInfo = QtWidgets.QPushButton(self.panel_left)
        self.pushButton_outputInfo.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_outputInfo.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(68, 67, 68);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton_outputInfo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_outputInfo.setIcon(icon3)
        self.pushButton_outputInfo.setObjectName("pushButton_outputInfo")
        self.horizontalLayout_output.addWidget(self.pushButton_outputInfo)
        self.layout_left.addLayout(self.horizontalLayout_output)
        self.pushButton_outputDir = QtWidgets.QPushButton(self.panel_left)
        self.pushButton_outputDir.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(20, 51, 89);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(49, 110, 186);\n"
"}")
        self.pushButton_outputDir.setObjectName("pushButton_outputDir")
        self.layout_left.addWidget(self.pushButton_outputDir)
        self.textBrowser_outputDir = QtWidgets.QTextBrowser(self.panel_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_outputDir.sizePolicy().hasHeightForWidth())
        self.textBrowser_outputDir.setSizePolicy(sizePolicy)
        self.textBrowser_outputDir.setMaximumSize(QtCore.QSize(300, 40))
        self.textBrowser_outputDir.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_outputDir.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser_outputDir.setObjectName("textBrowser_outputDir")
        self.layout_left.addWidget(self.textBrowser_outputDir)
        self.line_bottomLeft = QtWidgets.QFrame(self.panel_left)
        self.line_bottomLeft.setStyleSheet("background-color: rgb(68, 67, 68);")
        self.line_bottomLeft.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_bottomLeft.setLineWidth(1)
        self.line_bottomLeft.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_bottomLeft.setObjectName("line_bottomLeft")
        self.layout_left.addWidget(self.line_bottomLeft)
        self.horizontalLayout_configurator = QtWidgets.QHBoxLayout()
        self.horizontalLayout_configurator.setObjectName("horizontalLayout_configurator")
        self.label_configurator = QtWidgets.QLabel(self.panel_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_configurator.sizePolicy().hasHeightForWidth())
        self.label_configurator.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_configurator.setFont(font)
        self.label_configurator.setObjectName("label_configurator")
        self.horizontalLayout_configurator.addWidget(self.label_configurator)
        self.pushButton = QtWidgets.QPushButton(self.panel_left)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(68, 67, 68);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_configurator.addWidget(self.pushButton)
        self.layout_left.addLayout(self.horizontalLayout_configurator)
        self.gridLayout_topRight = QtWidgets.QGridLayout()
        self.gridLayout_topRight.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_topRight.setObjectName("gridLayout_topRight")
        self.spinBox_radius = QtWidgets.QSpinBox(self.panel_left)
        self.spinBox_radius.setObjectName("spinBox_radius")
        self.gridLayout_topRight.addWidget(self.spinBox_radius, 1, 2, 1, 1)
        self.pushButton_defEdge = QtWidgets.QPushButton(self.panel_left)
        self.pushButton_defEdge.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(68, 67, 68);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton_defEdge.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_defEdge.setIcon(icon4)
        self.pushButton_defEdge.setObjectName("pushButton_defEdge")
        self.gridLayout_topRight.addWidget(self.pushButton_defEdge, 3, 3, 1, 1)
        self.label_smoothiter = QtWidgets.QLabel(self.panel_left)
        self.label_smoothiter.setObjectName("label_smoothiter")
        self.gridLayout_topRight.addWidget(self.label_smoothiter, 2, 0, 1, 1)
        self.pushButton_defSmoothiter = QtWidgets.QPushButton(self.panel_left)
        self.pushButton_defSmoothiter.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(68, 67, 68);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton_defSmoothiter.setText("")
        self.pushButton_defSmoothiter.setIcon(icon4)
        self.pushButton_defSmoothiter.setObjectName("pushButton_defSmoothiter")
        self.gridLayout_topRight.addWidget(self.pushButton_defSmoothiter, 2, 3, 1, 1)
        self.horizontalSlider_radius = QtWidgets.QSlider(self.panel_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_radius.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_radius.setSizePolicy(sizePolicy)
        self.horizontalSlider_radius.setMaximumSize(QtCore.QSize(137, 16777215))
        self.horizontalSlider_radius.setAutoFillBackground(False)
        self.horizontalSlider_radius.setStyleSheet("")
        self.horizontalSlider_radius.setMaximum(600)
        self.horizontalSlider_radius.setSingleStep(50)
        self.horizontalSlider_radius.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_radius.setObjectName("horizontalSlider_radius")
        self.gridLayout_topRight.addWidget(self.horizontalSlider_radius, 1, 1, 1, 1)
        self.label_radius = QtWidgets.QLabel(self.panel_left)
        self.label_radius.setObjectName("label_radius")
        self.gridLayout_topRight.addWidget(self.label_radius, 1, 0, 1, 1)
        self.horizontalSlider_edge = QtWidgets.QSlider(self.panel_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_edge.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_edge.setSizePolicy(sizePolicy)
        self.horizontalSlider_edge.setMaximumSize(QtCore.QSize(137, 16777215))
        self.horizontalSlider_edge.setMaximum(50)
        self.horizontalSlider_edge.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_edge.setObjectName("horizontalSlider_edge")
        self.gridLayout_topRight.addWidget(self.horizontalSlider_edge, 3, 1, 1, 1)
        self.label_edge = QtWidgets.QLabel(self.panel_left)
        self.label_edge.setObjectName("label_edge")
        self.gridLayout_topRight.addWidget(self.label_edge, 3, 0, 1, 1)
        self.horizontalSlider_smoothiter = QtWidgets.QSlider(self.panel_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_smoothiter.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_smoothiter.setSizePolicy(sizePolicy)
        self.horizontalSlider_smoothiter.setMaximumSize(QtCore.QSize(137, 16777215))
        self.horizontalSlider_smoothiter.setMaximum(10)
        self.horizontalSlider_smoothiter.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_smoothiter.setObjectName("horizontalSlider_smoothiter")
        self.gridLayout_topRight.addWidget(self.horizontalSlider_smoothiter, 2, 1, 1, 1)
        self.pushButton_defRadius = QtWidgets.QPushButton(self.panel_left)
        self.pushButton_defRadius.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(68, 67, 68);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton_defRadius.setText("")
        self.pushButton_defRadius.setIcon(icon4)
        self.pushButton_defRadius.setObjectName("pushButton_defRadius")
        self.gridLayout_topRight.addWidget(self.pushButton_defRadius, 1, 3, 1, 1)
        self.spinBox_smoothiter = QtWidgets.QSpinBox(self.panel_left)
        self.spinBox_smoothiter.setObjectName("spinBox_smoothiter")
        self.gridLayout_topRight.addWidget(self.spinBox_smoothiter, 2, 2, 1, 1)
        self.spinBox_edge = QtWidgets.QSpinBox(self.panel_left)
        self.spinBox_edge.setObjectName("spinBox_edge")
        self.gridLayout_topRight.addWidget(self.spinBox_edge, 3, 2, 1, 1)
        self.layout_left.addLayout(self.gridLayout_topRight)
        self.pushButton_start = QtWidgets.QPushButton(self.panel_left)
        self.pushButton_start.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(41, 83, 144);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(49, 110, 186);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.layout_left.addWidget(self.pushButton_start)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_left.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.panel_left)
        self.panel_mid = QtWidgets.QVBoxLayout()
        self.panel_mid.setObjectName("panel_mid")
        self.horizontalLayout_viewer = QtWidgets.QHBoxLayout()
        self.horizontalLayout_viewer.setObjectName("horizontalLayout_viewer")
        self.label_viewer = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_viewer.setFont(font)
        self.label_viewer.setTextFormat(QtCore.Qt.RichText)
        self.label_viewer.setScaledContents(False)
        self.label_viewer.setIndent(0)
        self.label_viewer.setObjectName("label_viewer")
        self.horizontalLayout_viewer.addWidget(self.label_viewer)
        self.pushButton_viewerInfo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_viewerInfo.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_viewerInfo.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(68, 67, 68);\n"
"}\n"
"QPushButton{\n"
"    border: 10px;\n"
"}")
        self.pushButton_viewerInfo.setText("")
        self.pushButton_viewerInfo.setIcon(icon3)
        self.pushButton_viewerInfo.setObjectName("pushButton_viewerInfo")
        self.horizontalLayout_viewer.addWidget(self.pushButton_viewerInfo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_viewer.addItem(spacerItem2)
        self.gridLayout_midTop = QtWidgets.QGridLayout()
        self.gridLayout_midTop.setObjectName("gridLayout_midTop")
        self.checkBox_autoResume = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_autoResume.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_autoResume.setObjectName("checkBox_autoResume")
        self.gridLayout_midTop.addWidget(self.checkBox_autoResume, 2, 1, 1, 1)
        self.checkBox_disableView = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_disableView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_disableView.setObjectName("checkBox_disableView")
        self.gridLayout_midTop.addWidget(self.checkBox_disableView, 1, 1, 1, 1)
        self.horizontalLayout_viewer.addLayout(self.gridLayout_midTop)
        self.panel_mid.addLayout(self.horizontalLayout_viewer)
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGLWidget.sizePolicy().hasHeightForWidth())
        self.openGLWidget.setSizePolicy(sizePolicy)
        self.openGLWidget.setObjectName("openGLWidget")
        self.panel_mid.addWidget(self.openGLWidget)
        self.horizontalLayout_midBottom = QtWidgets.QHBoxLayout()
        self.horizontalLayout_midBottom.setObjectName("horizontalLayout_midBottom")
        self.pushButton_DontSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DontSave.setEnabled(False)
        self.pushButton_DontSave.setStyleSheet("QPushButton::hover{\n"
"    \n"
"    background-color: rgb(112, 27, 14);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(148, 17, 0);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton_DontSave.setObjectName("pushButton_DontSave")
        self.horizontalLayout_midBottom.addWidget(self.pushButton_DontSave)
        self.pushButton_saveAndContinue = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveAndContinue.setEnabled(False)
        self.pushButton_saveAndContinue.setStyleSheet("QPushButton::hover{\n"
"    background-color: rgb(31, 72, 51);\n"
"}\n"
"QPushButton{    \n"
"    background-color: rgb(57, 130, 92);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton_saveAndContinue.setObjectName("pushButton_saveAndContinue")
        self.horizontalLayout_midBottom.addWidget(self.pushButton_saveAndContinue)
        self.panel_mid.addLayout(self.horizontalLayout_midBottom)
        self.horizontalLayout.addLayout(self.panel_mid)
        self.panel_right = QtWidgets.QFrame(self.centralwidget)
        self.panel_right.setObjectName("panel_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.panel_right)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_activityMonitor = QtWidgets.QLabel(self.panel_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_activityMonitor.sizePolicy().hasHeightForWidth())
        self.label_activityMonitor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_activityMonitor.setFont(font)
        self.label_activityMonitor.setIndent(0)
        self.label_activityMonitor.setObjectName("label_activityMonitor")
        self.verticalLayout.addWidget(self.label_activityMonitor)
        self.label_avgProcessTime = QtWidgets.QLabel(self.panel_right)
        self.label_avgProcessTime.setObjectName("label_avgProcessTime")
        self.verticalLayout.addWidget(self.label_avgProcessTime)
        self.label_processTime = QtWidgets.QLabel(self.panel_right)
        self.label_processTime.setObjectName("label_processTime")
        self.verticalLayout.addWidget(self.label_processTime)
        self.label_numProcessed = QtWidgets.QLabel(self.panel_right)
        self.label_numProcessed.setObjectName("label_numProcessed")
        self.verticalLayout.addWidget(self.label_numProcessed)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.panel_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStyleSheet("background-color: rgb(51, 109, 186);")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionActivity_Monitor = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionActivity_Monitor.setIcon(icon5)
        self.actionActivity_Monitor.setObjectName("actionActivity_Monitor")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SAS Post-processing Program"))
        self.pushButton_inputDir.setText(_translate("MainWindow", "Select Input Directory"))
        self.textBrowser_inputDir.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Input Dir:</p></body></html>"))
        self.checkBox_saveToSameDir.setText(_translate("MainWindow", "Save to Same Directory"))
        self.pushButton_outputDir.setText(_translate("MainWindow", "Select Output Directory"))
        self.textBrowser_outputDir.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Output Dir:</p></body></html>"))
        self.label_configurator.setText(_translate("MainWindow", "Configurator"))
        self.label_smoothiter.setText(_translate("MainWindow", "Smoothiter"))
        self.label_radius.setText(_translate("MainWindow", "Radius"))
        self.label_edge.setText(_translate("MainWindow", "Edge Length"))
        self.pushButton_start.setText(_translate("MainWindow", "START"))
        self.label_viewer.setText(_translate("MainWindow", "Viewer"))
        self.checkBox_autoResume.setText(_translate("MainWindow", "Auto Resume"))
        self.checkBox_disableView.setText(_translate("MainWindow", "Disable Viewer"))
        self.pushButton_DontSave.setText(_translate("MainWindow", "Don\'t Save"))
        self.pushButton_saveAndContinue.setText(_translate("MainWindow", "Save and Continue"))
        self.label_activityMonitor.setText(_translate("MainWindow", "Activity Monitor"))
        self.label_avgProcessTime.setText(_translate("MainWindow", "Average process time: 0 seconds"))
        self.label_processTime.setText(_translate("MainWindow", "Process time: 0 seconds"))
        self.label_numProcessed.setText(_translate("MainWindow", "Number of processed scans: 0"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionActivity_Monitor.setText(_translate("MainWindow", "Activity Monitor"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
